'use client'

import { createContext, useContext, useState, useEffect, ReactNode } from 'react'

export type Lang = 'en' | 'ms' | 'zh'

// ── Full translation dictionary ───────────────────────────────────────────────
export const TRANSLATIONS = {
  en: {
    // Nav
    nav_dashboard:    'Dashboard',
    nav_awareness:    'Awareness',
    nav_alerts:       'Alerts',
    nav_detect:       'Voice Detector',
    nav_monitor:      'Call Monitor',
    nav_soon:         'Soon',
    nav_signout:      'Sign out',

    // Greetings
    greet_morning:    'Good morning',
    greet_afternoon:  'Good afternoon',
    greet_evening:    'Good evening',
    greet_night:      'Good night',
    greet_sub_morning:   'Start your day scam-aware and protected.',
    greet_sub_afternoon: 'Stay alert — most scam calls happen in the afternoon.',
    greet_sub_evening:   'Relax, but keep your guard up.',
    greet_sub_night:     'Rest well — VoiceGuard is watching over you.',

    // Monitor banner
    monitor_title:    'AI Voice Phishing Detector',
    monitor_sub:      'Real-time voice analysis will be available in the next release. Stay tuned!',
    monitor_soon:     'Coming Soon',

    // Awareness Hub
    hub_ai_badge:     'AI-Powered · Gemini',
    hub_title:        'Awareness Hub',
    hub_sub:          'Plain-language guides, real scam stories, and live cybersecurity news — written so anyone can understand and act.',
    hub_cta:          'Open Awareness Hub',
    topic_verify:     '"Is This Call Real?" — How to Tell',
    topic_ai:         "They Copied My Child's Voice?!",
    topic_tactics:    'Common Tricks Scammers Use on Elders',
    topic_action:     'Step-by-Step: What To Do Right Now',
    topic_family:     'Share This With Your Family',
    topic_local:      'Latest Scam Warnings Near You',
    tag_verify:       'Verify',
    tag_ai_threat:    'AI Threat',
    tag_tactics:      'Tactics',
    tag_action:       'Action',
    tag_family:       'Family',
    tag_local:        'Local',

    // Quiz
    quiz_label:       'Daily Safety Quiz',
    quiz_sub:         'Questions from the security database',
    quiz_from_db:     'Questions from the security database',
    quiz_done_title:  'All done for today!',
    quiz_done_sub:    'Come back tomorrow for new questions.',
    quiz_score_label: 'correct',
    quiz_pts_earned:  'points earned this session!',
    quiz_perfect:     'Perfect! You are scam-aware. Share this with family!',
    quiz_good:        'Good job! Review the tips and stay sharp.',
    quiz_keep:        'Keep practising — scammers are getting smarter too.',
    quiz_try_again:   'Try Again',
    quiz_learn_more:  'Learn More',
    quiz_next:        'Next Question →',
    quiz_see_score:   'See My Score',
    quiz_saving:      'saving…',
    quiz_difficulty_easy:   'easy',
    quiz_difficulty_medium: 'medium',
    quiz_difficulty_hard:   'hard',
    quiz_pts:         'pts',

    // Contacts
    contacts_title:   'Trusted Contacts',
    contacts_safe:    'Safe List',
    contacts_sub:     'If you get a suspicious call, hang up and contact one of these trusted people immediately.',
    contacts_empty_title: 'No contacts yet',
    contacts_empty_sub:   'Add a family member, doctor, or trusted neighbour.',
    contacts_add:     '+ Add Trusted Contact',
    contacts_save:    'Save Contact',
    contacts_saving:  'Saving…',
    contacts_name_ph: 'Full name (e.g. Ahmad — Son)',
    contacts_num_ph:  'Phone (e.g. +60 12-345 6789)',

    // Hotlines
    hotlines_title:   'Emergency Hotlines',
    hotlines_sub:     'Got scammed or feel unsafe? Call these official numbers — they are free.',

    // Video player
    video_label:      'Education Video',
    video_prev:       'Prev',
    video_next:       'Next',

    // Profile panel
    profile_account_info:   'Account Information',
    profile_display_name:   'Display Name',
    profile_email:          'Email',
    profile_account_type:   'Account Type',
    profile_free_plan:      'Free Plan',
    profile_member_since:   'Member Since',
    profile_quiz_summary:   'Quiz & Points Summary',
    profile_total_points:   'Total Points',
    profile_level:          'Level',
    profile_questions:      'Questions Answered',
    profile_correct:        'Correct Answers',
    profile_streak:         'Daily Streak',
    profile_days:           'days',
    profile_day:            'day',

    // Settings
    settings_notifications:      'Notifications',
    settings_notif_scam:         'Scam alert notifications',
    settings_notif_scam_desc:    'Get notified when a new scam alert is issued for your region',
    settings_notif_quiz:         'Daily quiz reminder',
    settings_notif_quiz_desc:    'A gentle reminder to complete today\'s safety quiz',
    settings_notif_digest:       'Weekly security digest',
    settings_notif_digest_desc:  'A weekly summary of cybersecurity news and scam trends',
    settings_notif_articles:     'New awareness articles',
    settings_notif_articles_desc:'Notify me when new guides are published in the Awareness Hub',
    settings_display:            'Display',
    settings_large_text:         'Large text mode',
    settings_large_text_desc:    'Increases base font size across the dashboard for easier reading',
    settings_high_contrast:      'High contrast mode',
    settings_high_contrast_desc: 'Boosts contrast and brightness for low-vision users',
    settings_simplified:         'Simplified interface',
    settings_simplified_desc:    'Hides advanced features and shows only essential controls',
    settings_preview_save:       '— preview on save',
    settings_privacy:            'Privacy',
    settings_anon:               'Share anonymised quiz data',
    settings_anon_desc:          'Helps improve question quality — no personal data is shared',
    settings_analytics:          'Usage analytics',
    settings_analytics_desc:     'Helps us understand how features are used to improve VoiceGuard',
    settings_save:               '💾 Save Settings',
    settings_saving:             'Saving…',
    settings_saved:              '✅ Settings saved!',
    settings_danger:             'Danger Zone',
    settings_delete:             '🗑️ Delete My Account',
    settings_delete_warn:        '⚠️ This cannot be undone',
    settings_delete_desc:        'All your data — points, contacts, and quiz history — will be permanently deleted. Type',
    settings_delete_to_confirm:  'to confirm.',
    settings_confirm_delete:     'Confirm Delete',
    settings_cancel:             'Cancel',

    // T&C
    tnc_title:         'Terms & Conditions',
    tnc_updated:       'Last updated: 1 January 2025',

    // Guidelines
    guide_title:       'VoiceGuard User Guidelines',
    guide_sub:         'How to use VoiceGuard safely and effectively',

    // Tabs
    tab_profile:    'Profile',
    tab_settings:   'Settings',
    tab_tnc:        'T&C',
    tab_guide:      'Guidelines',

    // Language switcher
    lang_label:  'Language',
    lang_en:     'English',
    lang_ms:     'Malay',
    lang_zh:     '中文',

    // ── Auth pages ──
    login_welcome:       'Welcome back',
    login_subtitle:      'Sign in to your account to continue protecting your calls.',
    login_email:         'Email address',
    login_email_ph:      'you@example.com',
    login_password:      'Password',
    login_forgot:        'Forgot password?',
    login_btn:           'Sign in',
    login_btn_loading:   'Signing in…',
    login_no_account:    "Don't have an account?",
    login_create:        'Create one',
    login_reset_success: 'Password updated! Sign in with your new password.',

    signup_title:        'Create your account',
    signup_subtitle:     'Join VoiceGuard and start protecting your calls from phishing.',
    signup_fullname:     'Full name',
    signup_fullname_ph:  'Ahmad bin Ali',
    signup_email:        'Email address',
    signup_email_ph:     'you@example.com',
    signup_password:     'Password',
    signup_password_ph:  'Min. 8 characters',
    signup_confirm:      'Confirm password',
    signup_confirm_ph:   '••••••••',
    signup_btn:          'Create account',
    signup_btn_loading:  'Creating account…',
    signup_have_account: 'Already have an account?',
    signup_signin:       'Sign in',
    signup_terms_pre:    'By creating an account you agree to our',
    signup_terms:        'Terms of Service',
    signup_and:          'and',
    signup_privacy:      'Privacy Policy',
    signup_pw_mismatch:  'Passwords do not match',
    signup_pw_short:     'Password must be at least 8 characters.',
    signup_pw_weak:      'Weak',
    signup_pw_fair:      'Fair',
    signup_pw_good:      'Good',
    signup_pw_strong:    'Strong',

    // Alerts page
    alerts_title:        'Alerts & Notifications',
    alerts_sub:          'Live cybersecurity alerts, scam warnings, and safety tips — powered by Gemini AI.',
    alerts_refresh:      'Refresh',
    alerts_loading:      'Loading…',
    alerts_retry:        'Retry in',
    alerts_live:         'Live AI alerts loaded',
    alerts_fallback:     'Showing curated fallback alerts — click Refresh to load live AI alerts',
    alerts_filter_all:   'All',
    alerts_filter_crit:  'Critical',
    alerts_filter_warn:  'Warning',
    alerts_filter_trend: 'Trend',
    alerts_filter_info:  'Info',
    alerts_filter_tip:   'Tip',
    alerts_read_more:    'Read more',
    alerts_show_less:    'Show less',
    alerts_dismiss:      'Dismiss',
    alerts_restore:      'Restore',
    alerts_dismissed:    'dismissed alert',
    alerts_dismissed_pl: 'dismissed alerts',
    alerts_empty:        'No alerts in this category.',
    alerts_empty_sub:    'Try a different filter or click Refresh.',

    // Awareness page
    awareness_title:     'Awareness Hub',
    awareness_sub:       'Stay ahead of voice phishing and cybersecurity threats with live AI-generated news, animated threat visuals, and region-specific alerts.',
    awareness_search_ph: 'Search threats, scams, country, or topic…',
    awareness_ai_search: 'AI Search',
    awareness_region:    'Filter by Region',
    awareness_category:  'Topic Category',
    awareness_curated:   'Curated News',
    awareness_ai_news:   'AI-Generated News',
    awareness_articles:  'articles',
    awareness_load_live: 'Load live AI news',
    awareness_read_full: 'Read full article',
    awareness_show_less: 'Show less',
    awareness_source:    'Source',
    awareness_key_label: 'Enter Gemini API Key',
    awareness_key_sub:   'Get a free key at',
    awareness_key_ph:    'AIza…',
    awareness_save_key:  'Save & Test Key',
    awareness_testing:   'Testing…',
    awareness_verified:  'Key verified',
    awareness_change_key:'Change key',

    // Voice Detector page
    detect_title:           'Voice Phishing Detector',
    detect_engine_online:   'Detection engine online',
    detect_engine_online_sub: 'Python API is running and ready.',
    detect_engine_offline:  'Python backend offline.',
    detect_engine_offline_sub: 'Run python api_server.py in the project root to start it.',
    detect_engine_checking: 'Checking Python inference backend…',
    detect_drop_title:      'Drop an audio file here',
    detect_drop_sub:        'WAV · FLAC · MP3 · M4A · OGG — or',
    detect_drop_browse:     'click to browse',
    detect_or:              'OR',
    detect_record_btn:      'Record Live Audio',
    detect_recording:       'Recording…',
    detect_stop_btn:        'Stop & Analyse',
    detect_tip:             'Tip: Speak or play the suspicious audio for 3–10 seconds, then stop.',
    detect_analysing:       'Analysing audio…',
    detect_failed_title:    'Analysis failed',
    detect_result_label:    'Detection Result',
    detect_result_fake_desc:'This audio shows strong signs of AI synthesis or voice cloning. It may be a deepfake used in a vishing attack.',
    detect_result_real_desc:'This audio appears to be genuine, natural human speech with no deepfake indicators detected.',
    detect_prob_real:       'Genuine voice (REAL)',
    detect_prob_fake:       'AI-generated (FAKE)',
    detect_scan_another:    'Scan Another File',
    detect_view_alerts:     'View Alerts',
    detect_learn_more:      'Learn More',
    detect_info_tip:        'Results are based on a 5-second audio clip. For best accuracy, provide a clear recording of the suspicious voice without background noise.',
    detect_history_title:   'Session History',
    detect_history_clear:   'Clear',
    detect_hist_file:       'File',
    detect_hist_result:     'Result',
    detect_hist_confidence: 'Confidence',
    detect_hist_time:       'Time',
    detect_how_title:       'How the Detection Works',
    detect_step1_title:     'Audio Input',
    detect_step1_desc:      'Upload or record any suspicious voice call or message',
    detect_step2_title:     'Wav2Vec2',
    detect_step2_desc:      'Pre-trained transformer extracts deep waveform features',
    detect_step3_title:     'CNN Spectrogram',
    detect_step3_desc:      'Residual CNN analyses the log-Mel spectrogram pattern',
    detect_step4_title:     'Fusion Head',
    detect_step4_desc:      'Both branches combine into a binary REAL / FAKE verdict',
    detect_stage1:          'Uploading audio…',
    detect_stage2:          'Pre-processing waveform…',
    detect_stage3:          'Running AI model…',
    detect_stage4:          'Generating result…',
  },

  ms: {
    nav_dashboard:    'Papan Pemuka',
    nav_awareness:    'Kesedaran',
    nav_alerts:       'Amaran',
    nav_detect:       'Pengesan Suara',
    nav_monitor:      'Monitor Panggilan',
    nav_soon:         'Segera',
    nav_signout:      'Log Keluar',

    greet_morning:    'Selamat pagi',
    greet_afternoon:  'Selamat tengah hari',
    greet_evening:    'Selamat petang',
    greet_night:      'Selamat malam',
    greet_sub_morning:   'Mulakan hari anda dengan sedar penipuan dan dilindungi.',
    greet_sub_afternoon: 'Berwaspada — kebanyakan panggilan scam berlaku pada waktu tengah hari.',
    greet_sub_evening:   'Berehat, tetapi tetap berwaspada.',
    greet_sub_night:     'Rehat dengan baik — VoiceGuard sentiasa menjaga anda.',

    monitor_title:    'Pengesan Panggilan Vishing AI',
    monitor_sub:      'Analisis suara masa nyata akan tersedia dalam keluaran seterusnya. Nantikan!',
    monitor_soon:     'Akan Datang',

    hub_ai_badge:     'Dikuasai AI · Gemini',
    hub_title:        'Hab Kesedaran',
    hub_sub:          'Panduan bahasa mudah, kisah penipuan sebenar, dan berita keselamatan siber terkini — ditulis supaya semua orang faham dan bertindak.',
    hub_cta:          'Buka Hab Kesedaran',
    topic_verify:     '"Adakah Panggilan Ini Benar?" — Cara Mengenal Pasti',
    topic_ai:         'Mereka Meniru Suara Anak Saya?!',
    topic_tactics:    'Helah Biasa Penipu Terhadap Warga Emas',
    topic_action:     'Langkah Demi Langkah: Apa Yang Perlu Dilakukan Sekarang',
    topic_family:     'Kongsi Ini Dengan Keluarga Anda',
    topic_local:      'Amaran Scam Terkini Di Kawasan Anda',
    tag_verify:       'Sahkan',
    tag_ai_threat:    'Ancaman AI',
    tag_tactics:      'Taktik',
    tag_action:       'Tindakan',
    tag_family:       'Keluarga',
    tag_local:        'Tempatan',

    quiz_label:       'Kuiz Keselamatan Harian',
    quiz_sub:         'Soalan dari pangkalan data keselamatan',
    quiz_from_db:     'Soalan dari pangkalan data keselamatan',
    quiz_done_title:  'Tahniah! Semua selesai hari ini!',
    quiz_done_sub:    'Kembali semula esok untuk soalan baru.',
    quiz_score_label: 'betul',
    quiz_pts_earned:  'mata diperoleh sesi ini!',
    quiz_perfect:     'Sempurna! Anda sedar tentang scam. Kongsikan dengan keluarga!',
    quiz_good:        'Bagus! Semak tip dan kekal berwaspada.',
    quiz_keep:        'Teruskan berlatih — penipu semakin bijak.',
    quiz_try_again:   'Cuba Lagi',
    quiz_learn_more:  'Ketahui Lebih Lanjut',
    quiz_next:        'Soalan Seterusnya →',
    quiz_see_score:   'Lihat Markah Saya',
    quiz_saving:      'menyimpan…',
    quiz_difficulty_easy:   'mudah',
    quiz_difficulty_medium: 'sederhana',
    quiz_difficulty_hard:   'susah',
    quiz_pts:         'mata',

    contacts_title:   'Kenalan Dipercayai',
    contacts_safe:    'Senarai Selamat',
    contacts_sub:     'Jika anda menerima panggilan mencurigakan, tutup telefon dan hubungi orang yang dipercayai ini segera.',
    contacts_empty_title: 'Tiada kenalan lagi',
    contacts_empty_sub:   'Tambah ahli keluarga, doktor, atau jiran yang dipercayai.',
    contacts_add:     '+ Tambah Kenalan Dipercayai',
    contacts_save:    'Simpan Kenalan',
    contacts_saving:  'Menyimpan…',
    contacts_name_ph: 'Nama penuh (cth. Ahmad — Anak)',
    contacts_num_ph:  'Telefon (cth. +60 12-345 6789)',

    hotlines_title:   'Talian Kecemasan',
    hotlines_sub:     'Ditipu atau rasa tidak selamat? Hubungi nombor rasmi ini — percuma.',

    video_label:      'Video Pendidikan',
    video_prev:       'Sebelum',
    video_next:       'Seterusnya',

    profile_account_info:   'Maklumat Akaun',
    profile_display_name:   'Nama Paparan',
    profile_email:          'E-mel',
    profile_account_type:   'Jenis Akaun',
    profile_free_plan:      'Pelan Percuma',
    profile_member_since:   'Ahli Sejak',
    profile_quiz_summary:   'Ringkasan Kuiz & Mata',
    profile_total_points:   'Jumlah Mata',
    profile_level:          'Tahap',
    profile_questions:      'Soalan Dijawab',
    profile_correct:        'Jawapan Betul',
    profile_streak:         'Rentetan Harian',
    profile_days:           'hari',
    profile_day:            'hari',

    settings_notifications:      'Pemberitahuan',
    settings_notif_scam:         'Pemberitahuan amaran scam',
    settings_notif_scam_desc:    'Dapatkan pemberitahuan apabila amaran scam baharu dikeluarkan untuk kawasan anda',
    settings_notif_quiz:         'Peringatan kuiz harian',
    settings_notif_quiz_desc:    'Peringatan lembut untuk melengkapkan kuiz keselamatan hari ini',
    settings_notif_digest:       'Digest keselamatan mingguan',
    settings_notif_digest_desc:  'Ringkasan berita keselamatan siber dan trend scam mingguan',
    settings_notif_articles:     'Artikel kesedaran baharu',
    settings_notif_articles_desc:'Maklumkan saya apabila panduan baharu diterbitkan dalam Hab Kesedaran',
    settings_display:            'Paparan',
    settings_large_text:         'Mod teks besar',
    settings_large_text_desc:    'Meningkatkan saiz fon asas di seluruh papan pemuka untuk bacaan yang lebih mudah',
    settings_high_contrast:      'Mod kontras tinggi',
    settings_high_contrast_desc: 'Meningkatkan kontras dan kecerahan untuk pengguna penglihatan terhad',
    settings_simplified:         'Antara muka ringkas',
    settings_simplified_desc:    'Menyembunyikan ciri lanjutan dan hanya menunjukkan kawalan penting',
    settings_preview_save:       '— pratonton semasa simpan',
    settings_privacy:            'Privasi',
    settings_anon:               'Kongsi data kuiz tanpa nama',
    settings_anon_desc:          'Membantu meningkatkan kualiti soalan — tiada data peribadi dikongsi',
    settings_analytics:          'Analitik penggunaan',
    settings_analytics_desc:     'Membantu kami memahami cara ciri digunakan untuk menambah baik VoiceGuard',
    settings_save:               '💾 Simpan Tetapan',
    settings_saving:             'Menyimpan…',
    settings_saved:              '✅ Tetapan disimpan!',
    settings_danger:             'Zon Bahaya',
    settings_delete:             '🗑️ Padam Akaun Saya',
    settings_delete_warn:        '⚠️ Ini tidak dapat dibatalkan',
    settings_delete_desc:        'Semua data anda — mata, kenalan, dan sejarah kuiz — akan dipadam secara kekal. Taip',
    settings_delete_to_confirm:  'untuk mengesahkan.',
    settings_confirm_delete:     'Sahkan Pemadaman',
    settings_cancel:             'Batal',

    tnc_title:         'Terma & Syarat',
    tnc_updated:       'Dikemaskini: 1 Januari 2025',

    guide_title:       'Garis Panduan Pengguna VoiceGuard',
    guide_sub:         'Cara menggunakan VoiceGuard dengan selamat dan berkesan',

    tab_profile:    'Profil',
    tab_settings:   'Tetapan',
    tab_tnc:        'T&S',
    tab_guide:      'Panduan',

    lang_label:  'Bahasa',
    lang_en:     'English',
    lang_ms:     'Melayu',
    lang_zh:     '中文',

    // ── Auth pages ──
    login_welcome:       'Selamat kembali',
    login_subtitle:      'Log masuk ke akaun anda untuk terus melindungi panggilan anda.',
    login_email:         'Alamat e-mel',
    login_email_ph:      'anda@contoh.com',
    login_password:      'Kata laluan',
    login_forgot:        'Lupa kata laluan?',
    login_btn:           'Log Masuk',
    login_btn_loading:   'Sedang log masuk…',
    login_no_account:    'Tiada akaun?',
    login_create:        'Daftar sekarang',
    login_reset_success: 'Kata laluan dikemas kini! Log masuk dengan kata laluan baharu anda.',

    signup_title:        'Cipta akaun anda',
    signup_subtitle:     'Sertai VoiceGuard dan mula melindungi panggilan anda daripada penipuan.',
    signup_fullname:     'Nama penuh',
    signup_fullname_ph:  'Ahmad bin Ali',
    signup_email:        'Alamat e-mel',
    signup_email_ph:     'anda@contoh.com',
    signup_password:     'Kata laluan',
    signup_password_ph:  'Min. 8 aksara',
    signup_confirm:      'Sahkan kata laluan',
    signup_confirm_ph:   '••••••••',
    signup_btn:          'Cipta akaun',
    signup_btn_loading:  'Mencipta akaun…',
    signup_have_account: 'Sudah ada akaun?',
    signup_signin:       'Log masuk',
    signup_terms_pre:    'Dengan mencipta akaun, anda bersetuju dengan',
    signup_terms:        'Terma Perkhidmatan',
    signup_and:          'dan',
    signup_privacy:      'Dasar Privasi',
    signup_pw_mismatch:  'Kata laluan tidak sepadan',
    signup_pw_short:     'Kata laluan mestilah sekurang-kurangnya 8 aksara.',
    signup_pw_weak:      'Lemah',
    signup_pw_fair:      'Sederhana',
    signup_pw_good:      'Baik',
    signup_pw_strong:    'Kuat',

    alerts_title:        'Amaran & Pemberitahuan',
    alerts_sub:          'Amaran keselamatan siber, peringatan scam, dan tip keselamatan secara langsung — dikuasakan oleh Gemini AI.',
    alerts_refresh:      'Muat Semula',
    alerts_loading:      'Memuatkan…',
    alerts_retry:        'Cuba semula dalam',
    alerts_live:         'Amaran AI langsung dimuatkan',
    alerts_fallback:     'Menunjukkan amaran terkurasi — klik Muat Semula untuk amaran AI langsung',
    alerts_filter_all:   'Semua',
    alerts_filter_crit:  'Kritikal',
    alerts_filter_warn:  'Amaran',
    alerts_filter_trend: 'Trend',
    alerts_filter_info:  'Maklumat',
    alerts_filter_tip:   'Tips',
    alerts_read_more:    'Baca lagi',
    alerts_show_less:    'Tunjukkan kurang',
    alerts_dismiss:      'Tutup',
    alerts_restore:      'Pulihkan',
    alerts_dismissed:    'amaran ditutup',
    alerts_dismissed_pl: 'amaran ditutup',
    alerts_empty:        'Tiada amaran dalam kategori ini.',
    alerts_empty_sub:    'Cuba penapis lain atau klik Muat Semula.',

    awareness_title:     'Hab Kesedaran',
    awareness_sub:       'Sentiasa berada di hadapan ancaman siber dengan berita yang dijana AI, visual ancaman animasi dan amaran khusus wilayah.',
    awareness_search_ph: 'Cari ancaman, scam, negara atau topik…',
    awareness_ai_search: 'Carian AI',
    awareness_region:    'Tapis mengikut Wilayah',
    awareness_category:  'Kategori Topik',
    awareness_curated:   'Berita Terkurasi',
    awareness_ai_news:   'Berita Jana AI',
    awareness_articles:  'artikel',
    awareness_load_live: 'Muat berita AI langsung',
    awareness_read_full: 'Baca artikel penuh',
    awareness_show_less: 'Tunjukkan kurang',
    awareness_source:    'Sumber',
    awareness_key_label: 'Masukkan Kunci API Gemini',
    awareness_key_sub:   'Dapatkan kunci percuma di',
    awareness_key_ph:    'AIza…',
    awareness_save_key:  'Simpan & Uji Kunci',
    awareness_testing:   'Menguji…',
    awareness_verified:  'Kunci disahkan',
    awareness_change_key:'Tukar kunci',

    // Voice Detector page
    detect_title:           'Pengesan Panggilan Vishing Suara',
    detect_engine_online:   'Enjin pengesanan dalam talian',
    detect_engine_online_sub: 'Python API sedang berjalan dan sedia.',
    detect_engine_offline:  'Bahagian belakang Python luar talian.',
    detect_engine_offline_sub: 'Jalankan python api_server.py di akar projek untuk memulakannya.',
    detect_engine_checking: 'Memeriksa bahagian belakang inferens Python…',
    detect_drop_title:      'Lepaskan fail audio di sini',
    detect_drop_sub:        'WAV · FLAC · MP3 · M4A · OGG — atau',
    detect_drop_browse:     'klik untuk semak imbas',
    detect_or:              'ATAU',
    detect_record_btn:      'Rakam Audio Langsung',
    detect_recording:       'Merakam…',
    detect_stop_btn:        'Berhenti & Analisis',
    detect_tip:             'Tip: Cakap atau mainkan audio yang mencurigakan selama 3–10 saat, kemudian berhenti.',
    detect_analysing:       'Menganalisis audio…',
    detect_failed_title:    'Analisis gagal',
    detect_result_label:    'Keputusan Pengesanan',
    detect_result_fake_desc:'Audio ini menunjukkan tanda kuat sintesis AI atau pengklonan suara. Ia mungkin deepfake yang digunakan dalam serangan vishing.',
    detect_result_real_desc:'Audio ini kelihatan sebagai pertuturan manusia yang tulen tanpa petunjuk deepfake yang dikesan.',
    detect_prob_real:       'Suara tulen (REAL)',
    detect_prob_fake:       'Dijana AI (FAKE)',
    detect_scan_another:    'Imbas Fail Lain',
    detect_view_alerts:     'Lihat Amaran',
    detect_learn_more:      'Ketahui Lebih Lanjut',
    detect_info_tip:        'Keputusan adalah berdasarkan klip audio 5 saat. Untuk ketepatan terbaik, berikan rakaman suara yang jelas tanpa bunyi latar.',
    detect_history_title:   'Sejarah Sesi',
    detect_history_clear:   'Padam',
    detect_hist_file:       'Fail',
    detect_hist_result:     'Keputusan',
    detect_hist_confidence: 'Keyakinan',
    detect_hist_time:       'Masa',
    detect_how_title:       'Cara Pengesanan Berfungsi',
    detect_step1_title:     'Input Audio',
    detect_step1_desc:      'Muat naik atau rakam sebarang panggilan atau mesej suara yang mencurigakan',
    detect_step2_title:     'Wav2Vec2',
    detect_step2_desc:      'Transformer pra-latih mengekstrak ciri gelombang mendalam',
    detect_step3_title:     'Spektrogram CNN',
    detect_step3_desc:      'CNN Residual menganalisis corak spektrogram log-Mel',
    detect_step4_title:     'Kepala Gabungan',
    detect_step4_desc:      'Kedua-dua cabang bergabung menjadi verdict binari REAL / FAKE',
    detect_stage1:          'Memuat naik audio…',
    detect_stage2:          'Pra-memproses gelombang…',
    detect_stage3:          'Menjalankan model AI…',
    detect_stage4:          'Menjana keputusan…',
  },

  zh: {
    nav_dashboard:    '控制面板',
    nav_awareness:    '安全意识',
    nav_alerts:       '警报',
    nav_detect:       '语音检测器',
    nav_monitor:      '通话监控',
    nav_soon:         '即将推出',
    nav_signout:      '退出登录',

    greet_morning:    '早上好',
    greet_afternoon:  '下午好',
    greet_evening:    '傍晚好',
    greet_night:      '晚上好',
    greet_sub_morning:   '从今天开始提高防骗意识，保护自己。',
    greet_sub_afternoon: '保持警惕——大多数诈骗电话发生在下午。',
    greet_sub_evening:   '放松一下，但仍需保持警惕。',
    greet_sub_night:     '好好休息——VoiceGuard 在守护您。',

    monitor_title:    'AI 语音诈骗检测器',
    monitor_sub:      '实时语音分析将在下一个版本中推出，敬请期待！',
    monitor_soon:     '即将推出',

    hub_ai_badge:     'AI 驱动 · Gemini',
    hub_title:        '安全意识中心',
    hub_sub:          '简明指南、真实诈骗案例和最新网络安全新闻——让每个人都能理解并采取行动。',
    hub_cta:          '打开意识中心',
    topic_verify:     '"这通电话是真的吗？"——如何判断',
    topic_ai:         'AI克隆了我孩子的声音！',
    topic_tactics:    '诈骗分子针对老年人的常见伎俩',
    topic_action:     '一步一步：现在该怎么做',
    topic_family:     '与家人分享这些信息',
    topic_local:      '您附近最新的诈骗警告',
    tag_verify:       '核实',
    tag_ai_threat:    'AI威胁',
    tag_tactics:      '手法',
    tag_action:       '行动',
    tag_family:       '家庭',
    tag_local:        '本地',

    quiz_label:       '每日安全问答',
    quiz_sub:         '来自安全数据库的题目',
    quiz_from_db:     '来自安全数据库的题目',
    quiz_done_title:  '今日全部完成！',
    quiz_done_sub:    '明天再来获取新题目。',
    quiz_score_label: '正确',
    quiz_pts_earned:  '本次获得积分！',
    quiz_perfect:     '完美！您具有防骗意识，请与家人分享！',
    quiz_good:        '做得好！复习提示并保持警觉。',
    quiz_keep:        '继续练习——诈骗分子越来越聪明了。',
    quiz_try_again:   '再试一次',
    quiz_learn_more:  '了解更多',
    quiz_next:        '下一题 →',
    quiz_see_score:   '查看我的得分',
    quiz_saving:      '保存中…',
    quiz_difficulty_easy:   '简单',
    quiz_difficulty_medium: '中等',
    quiz_difficulty_hard:   '困难',
    quiz_pts:         '积分',

    contacts_title:   '信任联系人',
    contacts_safe:    '安全名单',
    contacts_sub:     '若您接到可疑电话，请立即挂断并联系这些信任的人。',
    contacts_empty_title: '暂无联系人',
    contacts_empty_sub:   '添加家庭成员、医生或信任的邻居。',
    contacts_add:     '+ 添加信任联系人',
    contacts_save:    '保存联系人',
    contacts_saving:  '保存中…',
    contacts_name_ph: '全名（例：Ahmad — 儿子）',
    contacts_num_ph:  '电话（例：+60 12-345 6789）',

    hotlines_title:   '紧急热线',
    hotlines_sub:     '遭遇诈骗或感到不安全？拨打这些官方号码——免费。',

    video_label:      '教育视频',
    video_prev:       '上一个',
    video_next:       '下一个',

    profile_account_info:   '账户信息',
    profile_display_name:   '显示名称',
    profile_email:          '电子邮件',
    profile_account_type:   '账户类型',
    profile_free_plan:      '免费套餐',
    profile_member_since:   '注册时间',
    profile_quiz_summary:   '问答与积分摘要',
    profile_total_points:   '总积分',
    profile_level:          '等级',
    profile_questions:      '已回答题目',
    profile_correct:        '正确答案',
    profile_streak:         '每日连续',
    profile_days:           '天',
    profile_day:            '天',

    settings_notifications:      '通知',
    settings_notif_scam:         '诈骗警报通知',
    settings_notif_scam_desc:    '当您所在地区发布新诈骗警报时通知您',
    settings_notif_quiz:         '每日问答提醒',
    settings_notif_quiz_desc:    '温馨提醒您完成今天的安全问答',
    settings_notif_digest:       '每周安全摘要',
    settings_notif_digest_desc:  '每周网络安全新闻和诈骗趋势摘要',
    settings_notif_articles:     '新安全意识文章',
    settings_notif_articles_desc:'当意识中心发布新指南时通知我',
    settings_display:            '显示',
    settings_large_text:         '大字体模式',
    settings_large_text_desc:    '增大仪表板的基础字体大小，便于阅读',
    settings_high_contrast:      '高对比度模式',
    settings_high_contrast_desc: '提高对比度和亮度，适合视力不佳的用户',
    settings_simplified:         '简化界面',
    settings_simplified_desc:    '隐藏高级功能，只显示基本控件',
    settings_preview_save:       '— 保存时预览',
    settings_privacy:            '隐私',
    settings_anon:               '分享匿名问答数据',
    settings_anon_desc:          '帮助改善题目质量——不会分享个人数据',
    settings_analytics:          '使用分析',
    settings_analytics_desc:     '帮助我们了解功能使用情况以改进 VoiceGuard',
    settings_save:               '💾 保存设置',
    settings_saving:             '保存中…',
    settings_saved:              '✅ 设置已保存！',
    settings_danger:             '危险区域',
    settings_delete:             '🗑️ 删除我的账户',
    settings_delete_warn:        '⚠️ 此操作无法撤销',
    settings_delete_desc:        '您的所有数据——积分、联系人和问答记录——将被永久删除。请输入',
    settings_delete_to_confirm:  '以确认。',
    settings_confirm_delete:     '确认删除',
    settings_cancel:             '取消',

    tnc_title:         '条款与条件',
    tnc_updated:       '最后更新：2025年1月1日',

    guide_title:       'VoiceGuard 用户指南',
    guide_sub:         '如何安全有效地使用 VoiceGuard',

    tab_profile:    '个人资料',
    tab_settings:   '设置',
    tab_tnc:        '条款',
    tab_guide:      '指南',

    lang_label:  '语言',
    lang_en:     'English',
    lang_ms:     'Melayu',
    lang_zh:     '中文',

    // ── Auth pages ──
    login_welcome:       '欢迎回来',
    login_subtitle:      '登录您的账户，继续保护您的通话。',
    login_email:         '电子邮件地址',
    login_email_ph:      'you@example.com',
    login_password:      '密码',
    login_forgot:        '忘记密码？',
    login_btn:           '登录',
    login_btn_loading:   '登录中…',
    login_no_account:    '还没有账户？',
    login_create:        '立即注册',
    login_reset_success: '密码已更新！请使用新密码登录。',

    signup_title:        '创建您的账户',
    signup_subtitle:     '加入 VoiceGuard，开始保护您的通话免受诈骗。',
    signup_fullname:     '全名',
    signup_fullname_ph:  '张三',
    signup_email:        '电子邮件地址',
    signup_email_ph:     'you@example.com',
    signup_password:     '密码',
    signup_password_ph:  '至少 8 个字符',
    signup_confirm:      '确认密码',
    signup_confirm_ph:   '••••••••',
    signup_btn:          '创建账户',
    signup_btn_loading:  '创建中…',
    signup_have_account: '已有账户？',
    signup_signin:       '登录',
    signup_terms_pre:    '创建账户即表示您同意我们的',
    signup_terms:        '服务条款',
    signup_and:          '和',
    signup_privacy:      '隐私政策',
    signup_pw_mismatch:  '密码不匹配',
    signup_pw_short:     '密码至少需要 8 个字符。',
    signup_pw_weak:      '弱',
    signup_pw_fair:      '一般',
    signup_pw_good:      '良好',
    signup_pw_strong:    '强',

    alerts_title:        '警报与通知',
    alerts_sub:          '实时网络安全警报、诈骗警告和安全指南 — 由 Gemini AI 驱动。',
    alerts_refresh:      '刷新',
    alerts_loading:      '加载中…',
    alerts_retry:        '重试倒计时',
    alerts_live:         'AI 实时警报已加载',
    alerts_fallback:     '显示精选备用警报 — 点击刷新加载 AI 实时警报',
    alerts_filter_all:   '全部',
    alerts_filter_crit:  '紧急',
    alerts_filter_warn:  '警告',
    alerts_filter_trend: '趋势',
    alerts_filter_info:  '信息',
    alerts_filter_tip:   '提示',
    alerts_read_more:    '阅读更多',
    alerts_show_less:    '收起',
    alerts_dismiss:      '关闭',
    alerts_restore:      '恢复',
    alerts_dismissed:    '条已关闭警报',
    alerts_dismissed_pl: '条已关闭警报',
    alerts_empty:        '此类别暂无警报。',
    alerts_empty_sub:    '请尝试其他筛选条件或点击刷新。',

    awareness_title:     '安全意识中心',
    awareness_sub:       '通过 AI 生成的新闻、动态威胁可视化和地区层面警报，据安最新诈骗威胁。',
    awareness_search_ph: '搜索威胁、诈骗、国家或主题…',
    awareness_ai_search: 'AI 搜索',
    awareness_region:    '按地区筛选',
    awareness_category:  '主题类别',
    awareness_curated:   '精选新闻',
    awareness_ai_news:   'AI 生成新闻',
    awareness_articles:  '条文章',
    awareness_load_live: '加载 AI 实时新闻',
    awareness_read_full: '阅读全文',
    awareness_show_less: '收起',
    awareness_source:    '来源',
    awareness_key_label: '输入 Gemini API 密鑰',
    awareness_key_sub:   '免费获取密鑰',
    awareness_key_ph:    'AIza…',
    awareness_save_key:  '保存并测试密鑰',
    awareness_testing:   '测试中…',
    awareness_verified:  '密鑰已验证',
    awareness_change_key:'更换密鑰',

    // Voice Detector page
    detect_title:           '语音钓鱼检测器',
    detect_engine_online:   '检测引擎在线',
    detect_engine_online_sub: 'Python API 正在运行并准备就绪。',
    detect_engine_offline:  'Python 后端离线。',
    detect_engine_offline_sub: '在项目根目录运行 python api_server.py 以启动。',
    detect_engine_checking: '正在检查 Python 推理后端…',
    detect_drop_title:      '将音频文件拖放到此处',
    detect_drop_sub:        'WAV · FLAC · MP3 · M4A · OGG — 或',
    detect_drop_browse:     '点击浏览',
    detect_or:              '或',
    detect_record_btn:      '录制实时音频',
    detect_recording:       '录音中…',
    detect_stop_btn:        '停止并分析',
    detect_tip:             '提示：播放或朗读可疑音频 3–10 秒钟，然后停止。',
    detect_analysing:       '正在分析音频…',
    detect_failed_title:    '分析失败',
    detect_result_label:    '检测结果',
    detect_result_fake_desc:'此音频显示出强烈的 AI 合成或语音克隆迹象，可能是用于语音钓鱼攻击的深度伪造。',
    detect_result_real_desc:'此音频似乎是真实的自然人类语音，未检测到深度伪造迹象。',
    detect_prob_real:       '真实语音（REAL）',
    detect_prob_fake:       'AI生成（FAKE）',
    detect_scan_another:    '扫描其他文件',
    detect_view_alerts:     '查看警报',
    detect_learn_more:      '了解更多',
    detect_info_tip:        '结果基于 5 秒音频片段。为获得最佳准确度，请提供清晰无背景噪音的可疑语音录音。',
    detect_history_title:   '本次历史记录',
    detect_history_clear:   '清除',
    detect_hist_file:       '文件',
    detect_hist_result:     '结果',
    detect_hist_confidence: '置信度',
    detect_hist_time:       '时间',
    detect_how_title:       '检测原理',
    detect_step1_title:     '音频输入',
    detect_step1_desc:      '上传或录制任何可疑语音通话或消息',
    detect_step2_title:     'Wav2Vec2',
    detect_step2_desc:      '预训练 Transformer 提取深层波形特征',
    detect_step3_title:     'CNN 频谱图',
    detect_step3_desc:      '残差 CNN 分析 log-Mel 频谱图模式',
    detect_step4_title:     '融合头',
    detect_step4_desc:      '两个分支合并为二元 REAL / FAKE 判决',
    detect_stage1:          '正在上传音频…',
    detect_stage2:          '正在预处理波形…',
    detect_stage3:          '正在运行 AI 模型…',
    detect_stage4:          '正在生成结果…',
  },
} as const

export type TKey = keyof typeof TRANSLATIONS['en']

// ── Context ───────────────────────────────────────────────────────────────────
interface LangCtx {
  lang: Lang
  setLang: (l: Lang) => void
  t: (key: TKey) => string
}

const LangContext = createContext<LangCtx>({
  lang: 'en',
  setLang: () => {},
  t: (k) => TRANSLATIONS.en[k] ?? k,
})

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Lang>('en')

  // Load from localStorage on mount
  useEffect(() => {
    try {
      const saved = localStorage.getItem('vg_lang') as Lang | null
      if (saved && ['en','ms','zh'].includes(saved)) setLangState(saved)
    } catch {}
  }, [])

  const setLang = (l: Lang) => {
    setLangState(l)
    try { localStorage.setItem('vg_lang', l) } catch {}
  }

  const t = (key: TKey): string =>
    (TRANSLATIONS[lang] as Record<string, string>)[key]
    ?? (TRANSLATIONS.en as Record<string, string>)[key]
    ?? key

  return (
    <LangContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LangContext.Provider>
  )
}

export const useLang = () => useContext(LangContext)

// ── Language Switcher Component ───────────────────────────────────────────────
export function LanguageSwitcher({ compact = false }: { compact?: boolean }) {
  const { lang, setLang, t } = useLang()

  const options: { id: Lang; label: string; flag: string }[] = [
    { id: 'en', label: 'EN', flag: '🇬🇧' },
    { id: 'ms', label: 'BM', flag: '🇲🇾' },
    { id: 'zh', label: '中', flag: '🇨🇳' },
  ]

  return (
    <div style={{
      display: 'flex',
      alignItems: 'center',
      gap: 3,
      background: 'var(--bg-card)',
      border: '1px solid var(--border)',
      borderRadius: 99,
      padding: '3px 4px',
    }}>
      {options.map(opt => (
        <button
          key={opt.id}
          onClick={() => setLang(opt.id)}
          title={t(`lang_${opt.id}` as TKey)}
          style={{
            display: 'flex',
            alignItems: 'center',
            gap: compact ? 0 : 4,
            padding: compact ? '4px 8px' : '4px 10px',
            borderRadius: 99,
            border: 'none',
            cursor: 'pointer',
            fontFamily: "'Inter', sans-serif",
            fontSize: '.75rem',
            fontWeight: 700,
            transition: 'background .15s, color .15s',
            background: lang === opt.id
              ? 'linear-gradient(135deg, #6366f1, #8b5cf6)'
              : 'transparent',
            color: lang === opt.id ? 'white' : 'var(--text-muted)',
            boxShadow: lang === opt.id ? '0 2px 8px rgba(99,102,241,.35)' : 'none',
          }}
        >
          <span style={{ fontSize: '.85rem' }}>{opt.flag}</span>
          {!compact && <span>{opt.label}</span>}
        </button>
      ))}
    </div>
  )
}
